version: "3.8"
services:
# # Database
#   mongo:
#     image: mongo
#     ports:
#       - 27017:27017
#     volumes: 
#       - db_data:/data/db
#     environment: 
#       MONGODB_INITDB_ROOT_USERNAME: username
#       MONGODB_INITDB_ROOT_PASSWORD: password
#     networks:
#       - backend

# Backend
  backend:
    build: ./backend
    ports:
      - 5000:5000
    networks: 
      - backend
      - frontend

# Frontend
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    networks: 
      - frontend
# Isolation of communication between components of web app  
networks: 
  backend:
    driver: bridge
  frontend:
    driver: bridge

# volumes:
#   db_data: